### ISSUE TITLE
Reference Dockerfile from ansible playbook

### ISSUE THREAD

**Issue by tintinnabulate** [AaLondon/aalondon#130]
Just an idea, I'm a newbie to both docker and ansible, but it seems like we are repeating ourselves...

We have system provisioning information in two places:

1. Dockerfile
2. Ansible playbook

When really I think we can move the provisioning information into Dockerfile and just reference it from the playbook.

What do you think @chriswedgwood ?

**Comment by chriswedgwood** [comment]
yes we are provisioning in two different places but I think they need to be kept isolated from each other. If we wanted to be consistent we could use vagrant instead of docker?

There is probably a way to provision docker containers with ansible but I dont think its necessary in our case. As it stands any new dev joining the project will only need to be comfortable with docker and shouldn't need to worry about the ansible so much.

If I haven't understood can you show me by example what you mean?

**Comment by tintinnabulate** [comment]
Ah, I understand. Then I agree with you - I don't think it's necessary. I will close.
